%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB Version 9.6 (R2019a) and Database Toolbox Version 9.1 on 08-Oct-2019 13:12:46

%% Make connection to database
conn = database('MS SQL Server','souren','$souren$');

%Set query to execute on the database
query = ['SELECT WsTid, ' ...
    '	WsDateTime, ' ...
    '	AVT_01_004_1BL_P_kW ' ...
    'FROM ReEn4InPro.dbo."Wv$LiveData$AVT01" ' ...
    'WHERE WsTid > 13169140 AND WsTid %5 = 0'...
    'ORDER BY WsTid ASC'];

%% Execute query and fetch results
data = fetch(conn,query);

%% Close connection to database
close(conn)

%% Clear variables
clear conn query